name:                 pi-agent-space
version:              0.1.0.0
visibility:           public
id:                   pi-agent-space-0.1.0.0-inplace
key:                  pi-agent-space-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      AgentSpace
import-dirs:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/build

library-dirs:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/build

library-dirs-static:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/build

dynamic-library-dirs:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/build

data-dir:             /home/mikeco/projects/pi-agent-space/haskell/.
hs-libraries:         HSpi-agent-space-0.1.0.0-inplace
depends:              base-4.22.0.0-d187
haddock-interfaces:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/doc/html/pi-agent-space/pi-agent-space.haddock

haddock-html:
    /home/mikeco/projects/pi-agent-space/haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pi-agent-space-0.1.0.0/doc/html/pi-agent-space
